BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes*/*/*.bb \
             ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "pi-trustee"
BBFILE_PATTERN_pi-trustee := "^${LAYERDIR}/"
# meta-raspberrypi uses 9 priority, so any overrides need to be higher priority
BBFILE_PRIORITY_pi-trustee = "10"

LAYERSERIES_COMPAT_pi-trustee = "wrynose"
LAYERDEPENDS_pi-trustee = "core raspberrypi virtualization-layer"
