require conf/distro/poky.conf

DISTRO = "pi-trustee-distro"
DISTRO_VERSION = "1.0"

IMAGE_FSTYPES = "wic.bz2 wic.bmap"

DISTRO_FEATURES:append = " virtualization systemd systemd-compat-units usrmerge"
DISTRO_FEATURES:remove = "sysvinit"
VIRTUAL-RUNTIME_init_manager = "systemd"
DISTRO_FEATURES_OPTED_OUT = "sysvinit"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"
